### ISSUE TITLE
commands error out after fresh install of tool

### ISSUE THREAD

**Issue by scottaohara** [sinedied/a11y-ai#4]
Attempted to install this on my mac, running latest version of npm.

navigating to a folder and performing the command "a11y scan index.html" in terminal, I receive the following error:

```
file:///usr/local/lib/node_modules/a11y-ai/lib/cli.js:9
dns.setDefaultResultOrder('ipv4first');
    ^

TypeError: dns.setDefaultResultOrder is not a function
    at file:///usr/local/lib/node_modules/a11y-ai/lib/cli.js:9:5
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Similar errors occur regardless of the command used.  I'm at a loss for what to do here, since the installation / usage instructions are rather straight forward in their brevity, which is good.  but there's not much in the way to help when encountering errors like these.

**Comment by sinedied** [comment]
Which Node.js version are you using? (`node -v`)
It requires Node >= 16.4, might be the issue

**Comment by scottaohara** [comment]
that did help some, thanks.  i had a version of node prior to 16.4, so that's a good requirement to note.

after updating that and having a fresh install of playwrite, and axe-playwright i'm now getting this error:
>Could not scan issues for 'index.html': Error while running axe scan: Command failed: npx playwright test --config "/usr/local/lib/node_modules/a11y-ai/scan/playwright.config.cjs"

i'm just trying to do this all via the macOS terminal.  i'm clearly missing some steps here or something.  but the instructions as i can tell are now:

- [x] have latest node installed
- [x] have playwright and axe-playwright plugin installed.  
- [x] navigate to the folder / identify the file you wish to scan.  
- [x] run the command listed in the readme (`a11y scan index.html`) 

so i'm not sure what i'm missing at this point. any help would be appreciated since i can't do any tests with this until i figure out what's missing in the setup process.

**Comment by sinedied** [comment]
Thanks for the feedback!

Playwright and axe-playwright plugin should be installed along with the tool, so a separate install is not be needed.

Regarding your error, Playwright is probably missing its browser install, could you try running the command `npx playwright install chromium`?

Playwright usually takes care of that during the npm install, but it might depend of your system configuration.
Are you using npm or a different package manager? Are you using NVM or some kind of Node version manager?
This may help me update the doc and find out why the install missed some parts

**Comment by sinedied** [comment]
Closing this as it was solved after moving to NVM. The docs were updated to add this information

**Comment by scottaohara** [comment]
thanks again for the help on this.
